"""empty message

Revision ID: 69d2bd11f58f
Revises: 83b59d0cc8d7
Create Date: 2020-02-10 16:15:27.232352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69d2bd11f58f'
down_revision = '83b59d0cc8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('persons', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_index('email', table_name='persons')
    op.drop_index('username', table_name='persons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'persons', ['username'], unique=True)
    op.create_index('email', 'persons', ['email'], unique=True)
    op.alter_column('persons', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('persons', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
